name: Deploy Backend to Azure
on:
  push:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: npm install and build
        run: |
          cd backend
          npm install

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "kenyainspire-api"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend
